(() => {
'use strict';
if(document.getElementById('csu-weekly-extension'))return;
const C=globalThis.CSUWeeklyCore;
let fullNames=Object.create(null),nextSemester=false;
const semester=document.querySelector('#l_semester')?.textContent.trim();
const host=document.createElement('section');host.id='csu-weekly-extension';
const shadow=host.attachShadow({mode:'open'});
const style=document.createElement('style');
style.textContent=`
:host{display:block;color:#203849;font:14px/1.5 "PingFang TC","Microsoft JhengHei",sans-serif;margin:18px 0}*{box-sizing:border-box}.panel{background:#f3f7fa;border:1px solid #dce5eb;border-radius:10px;padding:20px}.top,.tools{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}h2{font-size:24px;margin:0;color:#203849}.hint{color:#617886;font-size:12px;margin:6px 0 14px}.tools{justify-content:flex-start;margin-bottom:16px}button,select{font:inherit;background:white;border:1px solid #b9ccd6;color:#203849;border-radius:6px;padding:8px 12px;cursor:pointer}button:hover{background:#e4f0f4}button:disabled{opacity:.4;cursor:default}:focus-visible{outline:3px solid #267b97;outline-offset:2px}.scroll{overflow:auto;border:1px solid #dce5eb;border-radius:8px;background:white}.grid{min-width:680px;display:grid;grid-template-columns:66px repeat(7,minmax(0,1fr))}.head{padding:11px 4px;text-align:center;background:white;border-bottom:1px solid #dce5eb}.head b,.head small{display:block}.head small{color:#657f8e}.today{background:#edf6f8}.slot{text-align:center;padding:15px 4px;color:#607988;font-size:12px;border-bottom:1px solid #e6edf1}.empty{border-left:1px solid #e6edf1;border-bottom:1px solid #e6edf1}.course{z-index:1;margin:3px 4px;padding:8px;border-radius:5px;border-left:3px solid var(--ink);background:var(--bg);color:var(--ink);overflow:auto;display:flex;flex-direction:column;gap:4px;min-width:0;overflow-wrap:anywhere}.course strong{font-size:14px;line-height:1.4}.course small{font-size:11px}.course .room{margin-top:auto}.note{font-size:11px;background:#ffffff88;padding:2px}.raw{white-space:pre-wrap;font-size:12px}.status{color:#637c8b;margin:12px 0 0;font-size:12px}.blank{padding:30px;color:#637c8b}.hidden{display:none}@media(max-width:650px){.panel{padding:12px}h2{font-size:20px}.tools{gap:6px}button,select{padding:8px}.grid{min-width:680px}}`;
// 放大視窗使用瀏覽器頂層 dialog，避免被原站的 overflow 或堆疊層遮住。
style.textContent += `
.details{border:1px solid #b9ccd6;border-radius:10px;max-width:min(460px,90vw);color:#203849;padding:22px}.details::backdrop{background:#142a3c66}.details p{white-space:pre-wrap;line-height:1.8}.course{cursor:pointer}.actions{display:flex;gap:8px;flex-wrap:wrap}.window{border:0;padding:0;border-radius:12px;width:calc(100vw - 24px);max-width:1600px;height:calc(100dvh - 24px);max-height:none;background:#f3f7fa;color:#203849}.window::backdrop{background:#142a3c99}.window .panel{height:100%;display:flex;flex-direction:column;padding:16px;border:0}.window .schedule{flex:1;min-height:0;display:flex;flex-direction:column}.window .schedule.hidden{display:none}.window .scroll{flex:1;min-height:0}.window .grid{height:100%;grid-template-rows:44px repeat(var(--period-count),minmax(32px,1fr))!important}.window .course{padding:4px 6px;gap:1px}.window .course strong{font-size:12px}.window .course small{font-size:11px}.window .slot{padding:5px}.window .head{padding:5px}.window .hint{margin:4px 0 8px}.window .tools{margin-bottom:8px}.window .status{margin-top:6px}.window .course .room{margin-top:0}.course:focus-visible{outline:2px solid #267b97;outline-offset:-2px}`;
style.textContent += `
.filters{width:min(460px,calc(100vw - 32px));max-height:85dvh;overflow:auto;border:1px solid #b9ccd6;border-radius:12px;padding:24px;color:#203849}.filters::backdrop{background:#142a3c66}.filters fieldset{border:1px solid #dce5eb;border-radius:8px;margin:18px 0;padding:12px;display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.filters label{display:flex;align-items:center;gap:8px;cursor:pointer}.filters input{width:18px;height:18px;accent-color:#267b97}.filters .filter-option{font-weight:600}.filters button{margin-right:8px}.details{width:min(560px,calc(100vw - 32px));max-width:none;max-height:85dvh;overflow:auto;padding:26px}.details h3{font-size:22px;line-height:1.55;margin:8px 0 18px;word-break:normal;overflow-wrap:anywhere}.detail-code{font-size:12px;color:#617886}.details p{font-size:15px;overflow-wrap:anywhere}.course{min-height:0;gap:5px}.course strong{display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:2;overflow:hidden;flex-shrink:0;word-break:normal;overflow-wrap:anywhere;line-height:1.5}.course small{flex-shrink:0;font-variant-numeric:tabular-nums}.window .course strong{font-size:13px;line-height:1.45}.window .course{gap:3px}.window .course small{font-size:11px}.window .course .room{margin-top:auto}`;
// 所有學校資料都用 textContent 插入，避免把課程文字當成 HTML 執行。
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
shadow.append(style);const panel=el('div',undefined,'panel');shadow.append(panel);
const top=el('div',undefined,'top');top.append(el('h2','我的週課表'));const actions=el('div',undefined,'actions');const filterButton=el('button','篩選');const expand=el('button','放大視窗');const toggle=el('button','顯示原始表格');actions.append(filterButton,expand,toggle);top.append(actions);panel.append(top,el('p','依網站實際日期顯示；連堂合併，保留教室與上課時間。','hint'));
const dialog=el('dialog',undefined,'window');dialog.setAttribute('aria-label','我的週課表放大視窗');shadow.append(dialog);
const details=el('dialog',undefined,'details');details.setAttribute('aria-label','課程詳細資訊');const detailText=el('div',undefined,'detail-content');const detailClose=el('button','關閉課程資訊');details.append(detailText,detailClose);shadow.append(details);detailClose.onclick=()=>details.close();
const filters={hiddenDays:[],hideEmptyDays:false,hideEmptyPeriods:false};
const filterDialog=el('dialog',undefined,'filters');filterDialog.setAttribute('aria-label','課表篩選');filterDialog.append(el('h2','課表篩選'),el('p','取消勾選即可隱藏星期；設定套用於目前頁面。','hint'));
const dayGroup=el('fieldset');dayGroup.append(el('legend','顯示星期'));const checks=[];
for(let d=0;d<7;d++){const label=el('label');const input=el('input');input.type='checkbox';input.checked=true;input.onchange=()=>{filters.hiddenDays=checks.flatMap((c,i)=>c.checked?[]:[i]);render();};checks.push(input);label.append(input,el('span','星期'+'一二三四五六日'[d]));dayGroup.append(label);}filterDialog.append(dayGroup);
function filterOption(key,title,description){const label=el('label',undefined,'filter-option');const input=el('input');input.type='checkbox';input.onchange=()=>{filters[key]=input.checked;render();};label.append(input,el('span',title));filterDialog.append(label,el('p',description,'hint'));return input;}
const emptyDays=filterOption('hideEmptyDays','隱藏無課日','隱藏目前這週整天沒有課的星期。');
const emptyPeriods=filterOption('hideEmptyPeriods','隱藏空白節次','隱藏所有已顯示星期都沒有課的節次。');
const resetFilters=el('button','全部顯示');const closeFilters=el('button','完成');filterDialog.append(resetFilters,closeFilters);shadow.append(filterDialog);
filterButton.onclick=()=>filterDialog.showModal();closeFilters.onclick=()=>filterDialog.close();resetFilters.onclick=()=>{checks.forEach(c=>c.checked=true);emptyDays.checked=emptyPeriods.checked=false;filters.hiddenDays=[];filters.hideEmptyDays=filters.hideEmptyPeriods=false;render();};
const body=el('div',undefined,'schedule');panel.append(body);const tools=el('div',undefined,'tools');const prev=el('button','‹ 上一週'),select=el('select'),current=el('button','本週'),next=el('button','下一週 ›');select.setAttribute('aria-label','選擇課表週次');tools.append(prev,select,current,next);body.append(tools);const scroll=el('div',undefined,'scroll');body.append(scroll);const status=el('p',undefined,'status');status.setAttribute('role','status');panel.append(status);
let table=null,model=null,weeks=[],selected=null,original=false,savedDisplay='',lastSignature='',timer;
const colors=[['#e5f0f6','#275e7b'],['#eeedf8','#625288'],['#f7eaf0','#935675'],['#e9f2e9','#456e4b'],['#fcf0dc','#8c6225']];
function today(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const value=k=>+parts.find(p=>p.type===k).value;return Date.UTC(value('year'),value('month')-1,value('day'));}
function label(t){const d=new Date(t);return `${d.getUTCFullYear()}/${d.getUTCMonth()+1}/${d.getUTCDate()}`;}
function applyVisibility(){if(table)table.style.display=original?savedDisplay:'none';body.classList.toggle('hidden',original);toggle.textContent=original?'顯示週課表':'顯示原始表格';}
function render(){scroll.replaceChildren();const index=weeks.indexOf(selected);prev.disabled=index<=0;next.disabled=index<0||index===weeks.length-1;select.value=String(selected);tools.classList.toggle('hidden',model?.mode==='weekly');tools.style.display=model?.mode==='weekly'?'none':'';if(!model?.days.length){scroll.append(el('div','目前沒有可顯示的課表，請使用網站的本學期／下學期選項。','blank'));status.textContent=model?.invalidRows?'有無法辨識的日期，請切回原始表格查看。':'資料僅在本頁處理。';return;}
const filtered=C.view(model,selected,filters);filterButton.textContent=filters.hiddenDays.length||filters.hideEmptyDays||filters.hideEmptyPeriods?'篩選（已套用）':'篩選';if(!filtered.weekdays.length||!filtered.indices.length){scroll.append(el('div','篩選後沒有可顯示的課程，請開啟右上角「篩選」，選擇「全部顯示」。','blank'));status.textContent='篩選只影響顯示，原始課表仍完整保留。';return;}
const grid=el('div',undefined,'grid');grid.style.gridTemplateColumns=`54px repeat(${filtered.weekdays.length},minmax(0,1fr))`;grid.style.minWidth=`${54+filtered.weekdays.length*105}px`;grid.style.setProperty('--period-count',filtered.indices.length);grid.style.gridTemplateRows=`58px repeat(${filtered.indices.length},104px)`;grid.setAttribute('aria-label','每週課表');scroll.append(grid);grid.append(el('div','節次','head'));const now=today();
for(const [column,i] of filtered.weekdays.entries()){const t=model.mode==='weekly'?null:selected+i*C.DAY;const h=el('div',undefined,'head'+(t===now?' today':''));h.style.gridColumn=column+2;h.style.gridRow=1;h.append(el('b','星期'+'一二三四五六日'[i]),el('small',t===null?'':label(t).split('/').slice(1).join('/')+(t===now?' 今天':'')));grid.append(h);}
filtered.indices.forEach((index,r)=>{const p=model.periods[index];const s=el('div',p+' 節','slot');s.style.gridColumn=1;s.style.gridRow=r+2;grid.append(s);for(const [column,d] of filtered.weekdays.entries()){const e=el('div',undefined,'empty'+(model.mode!=='weekly'&&selected+d*C.DAY===now?' today':''));e.style.gridColumn=column+2;e.style.gridRow=r+2;grid.append(e);}});
let count=0;for(const day of filtered.days){const d=day.weekday;if(d<0||d>6)continue;for(const source of day.blocks){const b=!nextSemester&&fullNames[source.code]?{...source,name:fullNames[source.code]}:source;count++;const card=el('article',undefined,'course');card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label',(b.name||'原始課程資料')+'：查看詳細資訊');card.onclick=()=>{detailText.replaceChildren();if(b.raw)detailText.append(el('p',b.raw));else{detailText.append(el('div',b.code,'detail-code'),el('h3',b.name),el('p',`上課時間　${b.start}–${b.end}\n教室　${b.room}`));if(b.note)detailText.append(el('p',b.note));if(/…|\.\.\./.test(b.name))detailText.append(el('p','此課名在原站已被截短，這裡保留原文。','hint'));}details.showModal();};card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();card.click();}};card.style.gridColumn=filtered.weekdays.indexOf(d)+2;card.style.gridRow=`${filtered.indices.indexOf(b.index)+2} / span ${b.span}`;const hash=Array.from(b.code||b.name||'').reduce((a,x)=>a+x.charCodeAt(0),0);const color=colors[hash%colors.length];card.style.setProperty('--bg',color[0]);card.style.setProperty('--ink',color[1]);if(b.raw)card.append(el('div',b.raw,'raw'));else{card.append(el('strong',b.name),el('small',`${b.start}–${b.end}`),el('small',`教室 ${b.room}`,'room'));if(b.note)card.append(el('div',b.note,'note'));card.title=`${b.code} ${b.name}\n${b.start}–${b.end}\n教室 ${b.room}\n${b.note}`;}grid.append(card);}}
status.textContent=(count?'週六鐘點可能與週間不同，以課程內的時間為準。':'這一週沒有排課。')+(model.invalidRows?' 有無法辨識的日期，請切回原始表格查看。':'')+(model.mode==='weekly'?' 原站提供固定週課表，未提供個別日期。':'')+' 點選課程可查看完整資訊。資料僅在本頁處理。';}
function refresh(){const found=document.querySelector('#stuTimetable');if(!found){if(table)table.style.display=savedDisplay;if(dialog.open)dialog.close();host.remove();table=null;lastSignature='';return;}
if(found!==table){if(table)table.style.display=savedDisplay;table=found;savedDisplay=table.style.display;lastSignature='';}
if(!host.isConnected)table.before(host);
const rows=Array.from(table.rows).map(r=>Array.from(r.cells).map(c=>{const copy=c.cloneNode(true);copy.querySelectorAll('br').forEach(br=>br.replaceWith('、'));return copy.textContent.trim();}));const signature=JSON.stringify(rows);if(signature===lastSignature)return;lastSignature=signature;
try{model=C.parse(rows[0]||[],rows.slice(1));const first=model.days[0]?.date,last=model.days.at(-1)?.date;weeks=[];if(first!==undefined)for(let w=C.monday(first);w<=C.monday(last);w+=7*C.DAY)weeks.push(w);if(!weeks.includes(selected)){const thisWeek=C.monday(today());selected=weeks.includes(thisWeek)?thisWeek:weeks[0];}select.replaceChildren();weeks.forEach(w=>{const o=el('option',`${label(w)} — ${label(w+6*C.DAY)}`);o.value=w;select.append(o);});select.disabled=!weeks.length;current.disabled=!weeks.includes(C.monday(today()));render();applyVisibility();}catch(error){original=true;applyVisibility();status.textContent='無法轉換此課表，已保留原始表格。';}}
function closeWindow(){if(dialog.open)dialog.close();}
dialog.addEventListener('close',()=>{shadow.insertBefore(panel,dialog);expand.textContent='放大視窗';expand.focus();});
expand.onclick=()=>{if(dialog.open){closeWindow();return;}original=false;applyVisibility();dialog.append(panel);expand.textContent='關閉視窗';dialog.showModal();expand.focus();};
toggle.onclick=()=>{closeWindow();original=!original;applyVisibility();};prev.onclick=()=>{selected=weeks[weeks.indexOf(selected)-1];render();};next.onclick=()=>{selected=weeks[weeks.indexOf(selected)+1];render();};current.onclick=()=>{selected=C.monday(today());render();};select.onchange=()=>{selected=Number(select.value);render();};
// 只用本學期成績頁補全同課號名稱；下學期不套用，避免跨學期誤配。
document.addEventListener('click',event=>{const href=event.target.closest('a')?.getAttribute('href')||'';const match=href.match(/showTimetable\(['"]([01])['"]\)/);if(match){nextSemester=match[1]==='1';if(model)render();}},true);
async function loadFullNames(){if(!semester||!document.querySelector('#stuTimetable'))return;try{const response=await fetch(new URL('min_stuScoreList.aspx',location.href),{credentials:'same-origin',redirect:'error',signal:AbortSignal.timeout(12000)});if(!response.ok)return;const doc=new DOMParser().parseFromString(await response.text(),'text/html');if(doc.querySelector('#l_semester')?.textContent.trim()!==semester)return;const rows=Array.from(doc.querySelectorAll('table.styled tbody tr')).map(r=>Array.from(r.cells).slice(0,2).map(c=>c.textContent.trim()));fullNames=C.courseNames(rows,semester);if(model)render();}catch{/* 查詢失敗仍保留原站名稱與課表。 */}}
loadFullNames();
// 學期切換以 AJAX 重建表格，監聽完成後重新解析；不重送 API。
new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(refresh,120);}).observe(document.body,{childList:true,subtree:true,characterData:true});refresh();
})();
