(() => {
'use strict';
if(document.getElementById('csu-weekly-extension'))return;
const C=globalThis.CSUWeeklyCore;
const host=document.createElement('section');host.id='csu-weekly-extension';
const shadow=host.attachShadow({mode:'open'});
const style=document.createElement('style');
style.textContent=`
:host{display:block;color:#203849;font:14px/1.5 "PingFang TC","Microsoft JhengHei",sans-serif;margin:18px 0}*{box-sizing:border-box}.panel{background:#f3f7fa;border:1px solid #dce5eb;border-radius:10px;padding:20px}.top,.tools{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}h2{font-size:24px;margin:0;color:#203849}.hint{color:#617886;font-size:12px;margin:6px 0 14px}.tools{justify-content:flex-start;margin-bottom:16px}button,select{font:inherit;background:white;border:1px solid #b9ccd6;color:#203849;border-radius:6px;padding:8px 12px;cursor:pointer}button:hover{background:#e4f0f4}button:disabled{opacity:.4;cursor:default}:focus-visible{outline:3px solid #267b97;outline-offset:2px}.scroll{overflow:auto;border:1px solid #dce5eb;border-radius:8px;background:white}.grid{min-width:680px;display:grid;grid-template-columns:66px repeat(7,minmax(0,1fr))}.head{padding:11px 4px;text-align:center;background:white;border-bottom:1px solid #dce5eb}.head b,.head small{display:block}.head small{color:#657f8e}.today{background:#edf6f8}.slot{text-align:center;padding:15px 4px;color:#607988;font-size:12px;border-bottom:1px solid #e6edf1}.empty{border-left:1px solid #e6edf1;border-bottom:1px solid #e6edf1}.course{z-index:1;margin:3px 4px;padding:8px;border-radius:5px;border-left:3px solid var(--ink);background:var(--bg);color:var(--ink);overflow:auto;display:flex;flex-direction:column;gap:4px;min-width:0;overflow-wrap:anywhere}.course strong{font-size:14px;line-height:1.4}.course small{font-size:11px}.course .room{margin-top:auto}.note{font-size:11px;background:#ffffff88;padding:2px}.raw{white-space:pre-wrap;font-size:12px}.status{color:#637c8b;margin:12px 0 0;font-size:12px}.blank{padding:30px;color:#637c8b}.hidden{display:none}@media(max-width:650px){.panel{padding:12px}h2{font-size:20px}.tools{gap:6px}button,select{padding:8px}.grid{min-width:680px}}`;
// 放大視窗使用瀏覽器頂層 dialog，避免被原站的 overflow 或堆疊層遮住。
style.textContent += `
.details{border:1px solid #b9ccd6;border-radius:10px;max-width:min(460px,90vw);color:#203849;padding:22px}.details::backdrop{background:#142a3c66}.details p{white-space:pre-wrap;line-height:1.8}.course{cursor:pointer}.actions{display:flex;gap:8px;flex-wrap:wrap}.window{border:0;padding:0;border-radius:12px;width:calc(100vw - 24px);max-width:1600px;height:calc(100dvh - 24px);max-height:none;background:#f3f7fa;color:#203849}.window::backdrop{background:#142a3c99}.window .panel{height:100%;display:flex;flex-direction:column;padding:16px;border:0}.window .schedule{flex:1;min-height:0;display:flex;flex-direction:column}.window .schedule.hidden{display:none}.window .scroll{flex:1;min-height:0}.window .grid{height:100%;grid-template-rows:44px repeat(var(--period-count),minmax(32px,1fr))!important}.window .course{padding:4px 6px;gap:1px}.window .course strong{font-size:12px}.window .course small{font-size:11px}.window .slot{padding:5px}.window .head{padding:5px}.window .hint{margin:4px 0 8px}.window .tools{margin-bottom:8px}.window .status{margin-top:6px}.window .course .room{margin-top:0}.course:focus-visible{outline:2px solid #267b97;outline-offset:-2px}`;
// 所有學校資料都用 textContent 插入，避免把課程文字當成 HTML 執行。
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
shadow.append(style);const panel=el('div',undefined,'panel');shadow.append(panel);
const top=el('div',undefined,'top');top.append(el('h2','我的週課表'));const actions=el('div',undefined,'actions');const expand=el('button','放大視窗');const toggle=el('button','顯示原始表格');actions.append(expand,toggle);top.append(actions);panel.append(top,el('p','依網站實際日期顯示；連堂合併，保留教室與上課時間。','hint'));
const dialog=el('dialog',undefined,'window');dialog.setAttribute('aria-label','我的週課表放大視窗');shadow.append(dialog);
const details=el('dialog',undefined,'details');details.setAttribute('aria-label','課程詳細資訊');const detailText=el('p');const detailClose=el('button','關閉課程資訊');details.append(detailText,detailClose);shadow.append(details);detailClose.onclick=()=>details.close();
const body=el('div',undefined,'schedule');panel.append(body);const tools=el('div',undefined,'tools');const prev=el('button','‹ 上一週'),select=el('select'),current=el('button','本週'),next=el('button','下一週 ›');select.setAttribute('aria-label','選擇課表週次');tools.append(prev,select,current,next);body.append(tools);const scroll=el('div',undefined,'scroll');body.append(scroll);const status=el('p',undefined,'status');status.setAttribute('role','status');panel.append(status);
let table=null,model=null,weeks=[],selected=null,original=false,savedDisplay='',lastSignature='',timer;
const colors=[['#e5f0f6','#275e7b'],['#eeedf8','#625288'],['#f7eaf0','#935675'],['#e9f2e9','#456e4b'],['#fcf0dc','#8c6225']];
function today(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const value=k=>+parts.find(p=>p.type===k).value;return Date.UTC(value('year'),value('month')-1,value('day'));}
function label(t){const d=new Date(t);return `${d.getUTCFullYear()}/${d.getUTCMonth()+1}/${d.getUTCDate()}`;}
function applyVisibility(){if(table)table.style.display=original?savedDisplay:'none';body.classList.toggle('hidden',original);toggle.textContent=original?'顯示週課表':'顯示原始表格';}
function render(){scroll.replaceChildren();const index=weeks.indexOf(selected);prev.disabled=index<=0;next.disabled=index<0||index===weeks.length-1;select.value=String(selected);tools.classList.toggle('hidden',model?.mode==='weekly');tools.style.display=model?.mode==='weekly'?'none':'';if(!model?.days.length){scroll.append(el('div','目前沒有可顯示的課表，請使用網站的本學期／下學期選項。','blank'));status.textContent=model?.invalidRows?'有無法辨識的日期，請切回原始表格查看。':'資料僅在本頁處理。';return;}
const grid=el('div',undefined,'grid');grid.style.setProperty('--period-count',model.periods.length);grid.style.gridTemplateRows=`58px repeat(${model.periods.length},72px)`;grid.setAttribute('aria-label','每週課表');scroll.append(grid);grid.append(el('div','節次','head'));const now=today();
for(let i=0;i<7;i++){const t=model.mode==='weekly'?null:selected+i*C.DAY;const h=el('div',undefined,'head'+(t===now?' today':''));h.style.gridColumn=i+2;h.style.gridRow=1;h.append(el('b','星期'+'一二三四五六日'[i]),el('small',t===null?'':label(t).split('/').slice(1).join('/')+(t===now?' 今天':'')));grid.append(h);}
model.periods.forEach((p,r)=>{const s=el('div',p+' 節','slot');s.style.gridColumn=1;s.style.gridRow=r+2;grid.append(s);for(let d=0;d<7;d++){const e=el('div',undefined,'empty'+(model.mode!=='weekly'&&selected+d*C.DAY===now?' today':''));e.style.gridColumn=d+2;e.style.gridRow=r+2;grid.append(e);}});
let count=0;for(const day of model.days){const d=model.mode==='weekly'?day.weekday:(day.date-selected)/C.DAY;if(d<0||d>6)continue;for(const b of day.blocks){count++;const card=el('article',undefined,'course');card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label',(b.name||'原始課程資料')+'：查看詳細資訊');card.onclick=()=>{detailText.textContent=b.raw||`${b.code} ${b.name}\n${b.start}–${b.end}\n教室 ${b.room}\n${b.note}`;details.showModal();};card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();card.click();}};card.style.gridColumn=d+2;card.style.gridRow=`${b.index+2} / span ${b.span}`;const hash=Array.from(b.code||b.name||'').reduce((a,x)=>a+x.charCodeAt(0),0);const color=colors[hash%colors.length];card.style.setProperty('--bg',color[0]);card.style.setProperty('--ink',color[1]);if(b.raw)card.append(el('div',b.raw,'raw'));else{card.append(el('strong',b.name),el('small',`${b.start}–${b.end}`),el('small',`教室 ${b.room}`,'room'));if(b.note)card.append(el('div',b.note,'note'));card.title=`${b.code} ${b.name}\n${b.start}–${b.end}\n教室 ${b.room}\n${b.note}`;}grid.append(card);}}
status.textContent=(count?'週六鐘點可能與週間不同，以課程內的時間為準。':'這一週沒有排課。')+(model.invalidRows?' 有無法辨識的日期，請切回原始表格查看。':'')+(model.mode==='weekly'?' 原站提供固定週課表，未提供個別日期。':'')+' 點選課程可查看完整資訊。資料僅在本頁處理。';}
function refresh(){const found=document.querySelector('#stuTimetable');if(!found){if(table)table.style.display=savedDisplay;if(dialog.open)dialog.close();host.remove();table=null;lastSignature='';return;}
if(found!==table){if(table)table.style.display=savedDisplay;table=found;savedDisplay=table.style.display;lastSignature='';}
if(!host.isConnected)table.before(host);
const rows=Array.from(table.rows).map(r=>Array.from(r.cells).map(c=>{const copy=c.cloneNode(true);copy.querySelectorAll('br').forEach(br=>br.replaceWith('、'));return copy.textContent.trim();}));const signature=JSON.stringify(rows);if(signature===lastSignature)return;lastSignature=signature;
try{model=C.parse(rows[0]||[],rows.slice(1));const first=model.days[0]?.date,last=model.days.at(-1)?.date;weeks=[];if(first!==undefined)for(let w=C.monday(first);w<=C.monday(last);w+=7*C.DAY)weeks.push(w);if(!weeks.includes(selected)){const thisWeek=C.monday(today());selected=weeks.includes(thisWeek)?thisWeek:weeks[0];}select.replaceChildren();weeks.forEach(w=>{const o=el('option',`${label(w)} — ${label(w+6*C.DAY)}`);o.value=w;select.append(o);});select.disabled=!weeks.length;current.disabled=!weeks.includes(C.monday(today()));render();applyVisibility();}catch(error){original=true;applyVisibility();status.textContent='無法轉換此課表，已保留原始表格。';}}
function closeWindow(){if(dialog.open)dialog.close();}
dialog.addEventListener('close',()=>{shadow.insertBefore(panel,dialog);expand.textContent='放大視窗';expand.focus();});
expand.onclick=()=>{if(dialog.open){closeWindow();return;}original=false;applyVisibility();dialog.append(panel);expand.textContent='關閉視窗';dialog.showModal();expand.focus();};
toggle.onclick=()=>{closeWindow();original=!original;applyVisibility();};prev.onclick=()=>{selected=weeks[weeks.indexOf(selected)-1];render();};next.onclick=()=>{selected=weeks[weeks.indexOf(selected)+1];render();};current.onclick=()=>{selected=C.monday(today());render();};select.onchange=()=>{selected=Number(select.value);render();};
// 學期切換以 AJAX 重建表格，監聽完成後重新解析；不重送 API。
new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(refresh,120);}).observe(document.body,{childList:true,subtree:true,characterData:true});refresh();
})();
