(() => {
'use strict';
if(document.getElementById('csu-credit-filter'))return;
const F=globalThis.CSUFeatures;
function el(tag,text){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;}
function init(){const table=Array.from(document.querySelectorAll('table')).find(t=>{const h=Array.from(t.rows[0]?.cells||[]).map(c=>c.textContent.trim());return h.length===7&&h[0]==='學期'&&h[1].includes('課碼')&&h[3]==='選課別';});if(!table)return false;
const host=el('section');host.id='csu-credit-filter';const shadow=host.attachShadow({mode:'open'});const style=el('style',`:host{display:block;margin:14px 0;font:14px/1.6 "Microsoft JhengHei",sans-serif;color:#34404c}.box{padding:14px;background:#f0f3f6;border:1px solid #c2cbd3;border-radius:4px}.controls{display:flex;gap:12px;flex-wrap:wrap;align-items:end}label{display:flex;flex-direction:column;gap:4px;min-width:120px;flex:1}select,input,button{box-sizing:border-box;font:inherit;min-height:38px;padding:6px 9px;border:1px solid #acbac5;border-radius:3px;background:#fff;color:#34404c;min-width:0;max-width:100%}button{cursor:pointer;background:linear-gradient(#fff,#e1e7ec)}h2{font-size:16px;margin:0 0 10px}p{margin:10px 0 0;font-size:12px}label:has(input){flex:2}select:focus-visible,input:focus-visible,button:focus-visible{outline:2px solid #427bb5}@media(max-width:550px){.controls{display:grid;grid-template-columns:1fr 1fr}label{min-width:0}.search{grid-column:1/-1}select,input,button{min-height:44px}}`);shadow.append(style);const box=el('div');box.className='box';box.append(el('h2','歷年學分篩選'));const controls=el('div');controls.className='controls';box.append(controls);const fields={};for(const [key,title] of [['semester','學期'],['category','課別'],['status','修課狀況']]){const label=el('label',title),select=el('select');select.setAttribute('aria-label',title);label.append(select);controls.append(label);fields[key]=select;}
const searchLabel=el('label','課名／課碼');searchLabel.className='search';const search=el('input');search.type='search';search.placeholder='輸入課名或課碼';searchLabel.append(search);controls.append(searchLabel);const reset=el('button','清除篩選');reset.type='button';controls.append(reset);const status=el('p');status.setAttribute('role','status');box.append(status,el('p','上方學校實得學分累計不受篩選影響；表列學分含尚未取得及重修紀錄，不等於實得或畢業學分。'));shadow.append(box);table.before(host);
let records=[],others=[];
function apply(){const filter=Object.fromEntries(Object.entries(fields).map(([k,e])=>[k,e.value]));filter.query=search.value;let count=0,total=0;const active=Object.values(filter).some(Boolean);for(const {row,data,display} of records){const show=F.matchesCredit(data,filter);row.style.display=show?display:'none';if(show){count++;total+=data.credits||0;}}for(const {row,semester,display} of others){row.style.display=(!filter.category&&!filter.status&&!filter.query&&(!filter.semester||semester===filter.semester))?display:'none';}status.textContent=`顯示 ${count} / ${records.length} 筆課程紀錄；表列學分加總 ${Number(total.toFixed(2))}。`+(count===0?' 沒有符合條件的資料。':'')+(active?' 篩選中的課程不重算學校平均成績。':'');}
function read(){const displays=new Map([...records,...others].map(x=>[x.row,x.display]));records=[];others=[];for(const row of Array.from(table.rows).slice(1)){const cells=Array.from(row.cells).map(c=>c.textContent.trim()),data=F.creditRow(cells),display=displays.get(row)??row.style.display;if(data)records.push({row,data,display});else others.push({row,semester:cells[0],display});}for(const [key,select] of Object.entries(fields)){const previous=select.value;select.replaceChildren();const all=el('option','全部');all.value='';select.append(all);const values=[...new Set(records.map(r=>r.data[key]).filter(Boolean))].sort((a,b)=>key==='semester'?b.localeCompare(a):a.localeCompare(b,'zh-Hant'));for(const value of values){const option=el('option',value);option.value=value;select.append(option);}select.value=values.includes(previous)?previous:'';}apply();}
for(const select of Object.values(fields))select.onchange=apply;search.oninput=apply;reset.onclick=()=>{for(const s of Object.values(fields))s.value='';search.value='';apply();};new MutationObserver(read).observe(table,{childList:true,subtree:true,characterData:true});read();return true;}
if(!init()){const observer=new MutationObserver(()=>{if(init())observer.disconnect();});observer.observe(document.body,{childList:true,subtree:true});}
})();
