(() => {
'use strict';
// 原站桌面與手機選單共用 ID，優先使用桌面 accordion，不能取第一個 ID。
const mine=document.querySelector('nav:not(.phone) [id="dirMine"]')||Array.from(document.querySelectorAll('[id="dirMine"]')).find(e=>e.getClientRects().length),term=document.querySelector('#l_semester');
if(!mine||!term||document.querySelector('#csu-pins'))return;
const menu=mine.closest('li').parentElement;
// 只保存功能 ID；點擊時交回原站連結，保留原本的 SSO 與開窗行為。
const items=Array.from(menu.querySelectorAll('li > ul a[id]')).map(a=>({id:a.id,label:a.textContent.trim(),source:a,group:a.closest('ul').parentElement.querySelector(':scope > a')?.textContent.trim()||''}));
if(!items.length)return;
const section=document.createElement('li');section.id='csu-pins';
const title=document.createElement('a');title.href='#';title.className=mine.className;title.textContent='釘選功能';title.classList.add('open');title.setAttribute('aria-expanded','true');
const list=document.createElement('ul');list.className='sub';list.style.display='block';section.append(title,list);mine.closest('li').before(section);
// 原站以不同 nav 呈現手機與桌面；視窗改變時移動同一釘選區塊。
function placePins(){const visible=Array.from(document.querySelectorAll('[id="dirMine"]')).find(a=>a.getClientRects().length);if(visible&&section.nextElementSibling!==visible.closest('li'))visible.closest('li').before(section);}
placePins();window.addEventListener('resize',placePins);
title.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();const open=list.style.display!=='none';list.style.display=open?'none':'block';title.classList.toggle('open',!open);title.setAttribute('aria-expanded',String(!open));});
const termLink=term.closest('a');termLink.parentElement.classList.add('csu-term-actions');
const settings=document.createElement('button');settings.type='button';settings.id='csu-pin-settings';settings.textContent='設定釘選功能';termLink.after(settings);
const style=document.createElement('style');style.textContent=`.csu-term-actions{display:flex!important;align-items:center!important;gap:10px;white-space:nowrap}.csu-term-actions>a{flex:0 0 auto}.csu-term-actions>#csu-pin-settings{flex:0 0 auto;margin:0!important}#csu-pin-settings{font:inherit;font-size:12px;color:#fff;background:linear-gradient(#60758b,#354657);border:1px solid #273747;border-radius:3px;padding:6px 10px;margin-left:10px;cursor:pointer;vertical-align:middle}#csu-pins>ul>li>a{cursor:pointer}#csu-pins .csu-pin-empty{display:block;padding:10px 14px;color:#687480;font-size:12px}#csu-pin-settings:focus-visible{outline:2px solid #82b6ee;outline-offset:2px}`;document.head.append(style);
const host=document.createElement('div');const shadow=host.attachShadow({mode:'open'});document.body.append(host);
const css=document.createElement('style');css.textContent=`dialog{font:14px/1.6 "Microsoft JhengHei",sans-serif;color:#39434d;background:#f7f8fa;border:1px solid #9faab5;border-radius:4px;padding:0;width:min(620px,90vw);max-height:85vh}dialog::backdrop{background:#26384b80}h2{font-size:17px;margin:0;padding:12px 18px;background:linear-gradient(#f8fafc,#dce2e8);border-bottom:1px solid #bcc5ce}form{padding:16px}fieldset{border:1px solid #c8d0d7;margin:0 0 14px;padding:10px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}legend{font-weight:bold}label{display:flex;gap:8px;align-items:start;cursor:pointer}input{margin-top:5px;accent-color:#427bb5}button{font:inherit;border:1px solid #a1acb6;border-radius:3px;padding:6px 16px;margin-right:8px;background:linear-gradient(#fff,#e0e5ea);color:#34404c;cursor:pointer}p{margin:0 0 12px;color:#63717e}footer{position:sticky;bottom:0;padding:12px 0;background:#f7f8fa}button:focus-visible,input:focus-visible{outline:2px solid #427bb5;outline-offset:2px}@media(max-width:480px){fieldset{grid-template-columns:1fr}}`;shadow.append(css);
const dialog=document.createElement('dialog');dialog.setAttribute('aria-label','設定釘選功能');shadow.append(dialog);const heading=document.createElement('h2');heading.textContent='設定釘選功能';dialog.append(heading);const form=document.createElement('form');form.method='dialog';dialog.append(form);
const hint=document.createElement('p');hint.textContent='勾選左側功能，儲存後顯示於「熱門服務」上方。';form.append(hint);const checks=new Map();
for(const group of [...new Set(items.map(i=>i.group))]){const field=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=group;field.append(legend);for(const item of items.filter(i=>i.group===group)){const label=document.createElement('label'),input=document.createElement('input'),text=document.createElement('span');input.type='checkbox';text.textContent=item.label;checks.set(item.id,input);label.append(input,text);field.append(label);}form.append(field);}
const footer=document.createElement('footer'),save=document.createElement('button'),cancel=document.createElement('button');save.type='button';save.textContent='儲存';cancel.type='submit';cancel.textContent='取消';const reset=document.createElement('button');reset.type='button';reset.textContent='重置';reset.onclick=()=>{for(const input of checks.values())input.checked=false;hint.textContent='已取消所有勾選，按「儲存」套用；按「取消」保留原設定。';};footer.append(reset,save,cancel);form.append(footer);
let pins=[],ready=false;
function paint(){list.replaceChildren();for(const item of items.filter(i=>pins.includes(i.id))){const li=document.createElement('li'),a=document.createElement('a');li.className='with-icon';const icon=document.createElement('span');icon.className='icon icon-bookmark';a.textContent=item.label;a.prepend(icon);const href=item.source.getAttribute('href')||'#';a.href=href.startsWith('javascript:')?'#':item.source.href;a.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();item.source.click();});li.append(a);list.append(li);}if(!list.children.length){const li=document.createElement('li'),span=document.createElement('span');span.className='csu-pin-empty';span.textContent='尚未釘選，請使用上方設定按鈕。';li.append(span);list.append(li);}}
settings.disabled=true;
settings.onclick=()=>{if(!ready)return;hint.textContent='勾選左側功能，儲存後顯示於「熱門服務」上方。';for(const [id,input] of checks)input.checked=pins.includes(id);dialog.showModal();};
save.onclick=async()=>{const next=[...checks].filter(([,input])=>input.checked).map(([id])=>id);save.disabled=true;try{await chrome.storage.local.set({csuPinnedFunctions:next});pins=next;paint();dialog.close();}catch{hint.textContent='儲存失敗，請重新載入擴充功能後再試。';}finally{save.disabled=false;}};
chrome.storage.local.get('csuPinnedFunctions').then(data=>{pins=Array.isArray(data.csuPinnedFunctions)?data.csuPinnedFunctions.filter(x=>typeof x==='string'):[];ready=true;settings.disabled=false;paint();}).catch(()=>{paint();settings.disabled=false;hint.textContent='無法讀取設定，請重新載入擴充功能。';});
chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes.csuPinnedFunctions){pins=Array.isArray(changes.csuPinnedFunctions.newValue)?changes.csuPinnedFunctions.newValue:[];paint();}});
})();
