(() => {
'use strict';
// 原站桌面與手機選單共用 ID，優先使用桌面 accordion，不能取第一個 ID。
const mine=document.querySelector('nav:not(.phone) [id="dirMine"]')||Array.from(document.querySelectorAll('[id="dirMine"]')).find(e=>e.getClientRects().length),term=document.querySelector('#l_semester');
if(!mine||!term||document.querySelector('#csu-pins'))return;
const menu=mine.closest('li').parentElement;
// 只保存功能 ID；點擊時交回原站連結，保留原本的 SSO 與開窗行為。
const items=Array.from(menu.querySelectorAll('li > ul a[id]')).map(a=>({id:a.id,label:a.textContent.trim(),source:a,group:a.closest('ul').parentElement.querySelector(':scope > a')?.textContent.trim()||''}));
if(!items.length)return;
const section=document.createElement('li');section.id='csu-pins';
const title=document.createElement('a');title.href='#';title.className=mine.className;title.classList.add('open');title.setAttribute('aria-expanded','true');
// 原站標題使用 16px PNG 圖示；自繪 SVG 沿用相同尺寸與間距，避免依賴字型 class。
const svgNS='http://www.w3.org/2000/svg';const titleIcon=document.createElementNS(svgNS,'svg');titleIcon.setAttribute('viewBox','0 0 24 24');titleIcon.setAttribute('width','16');titleIcon.setAttribute('height','16');titleIcon.setAttribute('aria-hidden','true');titleIcon.classList.add('csu-pin-icon');const titleIconPath=document.createElementNS(svgNS,'path');titleIconPath.setAttribute('fill','currentColor');titleIconPath.setAttribute('d','M16 12V4h1V2H7v2h1v8l-2 2v2h5.2v6h1.6v-6H18v-2l-2-2z');titleIcon.append(titleIconPath);title.append(titleIcon,document.createTextNode('釘選功能'));
const list=document.createElement('ul');list.className='sub';list.style.display='block';section.append(title,list);mine.closest('li').before(section);
// 手機選單可能在載入後才展開；依可見選單移動同一區塊與設定入口，不依賴縮放。
function placePins(){const visible=Array.from(document.querySelectorAll('[id="dirMine"]')).find(a=>a.getClientRects().length);if(!visible)return;if(section.nextElementSibling!==visible.closest('li'))visible.closest('li').before(section);if(visible.closest('nav.phone')){if(settings.parentElement!==section)title.after(settings);}else if(settings.previousElementSibling!==termLink)termLink.after(settings);}
title.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();const open=list.style.display!=='none';list.style.display=open?'none':'block';title.classList.toggle('open',!open);title.setAttribute('aria-expanded',String(!open));});
const termLink=term.closest('a');termLink.parentElement.classList.add('csu-term-actions');
const settings=document.createElement('button');settings.type='button';settings.id='csu-pin-settings';settings.textContent='設定釘選功能';termLink.after(settings);
let placementFrame=0;function queuePlacement(){if(placementFrame)return;placementFrame=requestAnimationFrame(()=>{placementFrame=0;placePins();});}
placePins();window.addEventListener('resize',queuePlacement);new MutationObserver(queuePlacement).observe(document.body,{subtree:true,attributes:true,attributeFilter:['class','style','hidden']});
const style=document.createElement('style');style.textContent=`.csu-term-actions{display:flex!important;align-items:center!important;gap:10px;white-space:nowrap}.csu-term-actions>a{flex:0 0 auto}.csu-term-actions>#csu-pin-settings{flex:0 0 auto;margin:0!important}#csu-pin-settings{font:inherit;font-size:12px;color:#fff;background:linear-gradient(#60758b,#354657);border:1px solid #273747;border-radius:3px;padding:6px 10px;margin-left:10px;cursor:pointer;vertical-align:middle}#csu-pins>ul>li>a{cursor:pointer}#csu-pins .csu-pin-empty{display:block;padding:10px 14px;color:#687480;font-size:12px}#csu-pin-settings:focus-visible{outline:2px solid #82b6ee;outline-offset:2px}.csu-pin-icon{color:#dc2626;vertical-align:middle;margin-right:10px}`;document.head.append(style);
const host=document.createElement('div');const shadow=host.attachShadow({mode:'open'});document.body.append(host);
// 手機原站只替 a 畫背景；釘選容器必須自行包住按鈕與清單，避免內容透出。
style.textContent+=`nav.phone #csu-pins{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:0 8px;padding:8px 12px 0;margin:0;box-sizing:border-box;background:linear-gradient(#394758,#1e2a39);border:1px solid #111b27;border-radius:3px 3px 0 0;color:#ccd1d8;overflow:hidden}nav.phone #csu-pins>a{display:flex;align-items:center;gap:8px;min-height:44px;padding:0;border:0;border-radius:0;background:none;box-shadow:none;text-shadow:0 1px #111b27;color:#eef2f6;font-size:15px;font-weight:bold;white-space:nowrap;text-decoration:none}nav.phone #csu-pins>a::before,nav.phone #csu-pins>a::after{display:none}nav.phone #csu-pins .csu-pin-icon{flex:none;margin:0;color:#f87171}nav.phone #csu-pins>#csu-pin-settings{min-height:44px;margin:0;padding:6px 10px;border:1px solid #788a9e;border-radius:3px;background:linear-gradient(#52677e,#354657);color:#fff;font-size:12px;text-shadow:none;box-shadow:none}nav.phone #csu-pins>ul{grid-column:1/-1;margin:8px -12px 0;padding:0;list-style:none;border-top:1px solid #172331;background:#3b4658}nav.phone #csu-pins>ul>li{margin:0;padding:0;list-style:none;background:none}nav.phone #csu-pins>ul>li>a{display:flex;align-items:center;gap:8px;min-height:44px;box-sizing:border-box;padding:10px 14px;border:0;border-bottom:1px solid #2a3647;border-radius:0;background:#3b4658;color:#f0f3f7;text-shadow:none;box-shadow:none;line-height:1.5;overflow-wrap:anywhere;text-decoration:none}nav.phone #csu-pins>ul>li>a::after{display:none}nav.phone #csu-pins>ul>li>a:hover{background:#475468}nav.phone #csu-pins .csu-pin-empty{padding:14px;font-size:13px;line-height:1.6;white-space:normal;color:#d3dce6}nav.phone #csu-pins a:focus-visible{outline:2px solid #82b6ee;outline-offset:-3px}`;
const css=document.createElement('style');css.textContent=`dialog{font:14px/1.6 "Microsoft JhengHei",sans-serif;color:#39434d;background:#f7f8fa;border:1px solid #9faab5;border-radius:4px;padding:0;width:min(620px,90vw);max-height:85vh}dialog::backdrop{background:#26384b80}h2{font-size:17px;margin:0;padding:12px 18px;background:linear-gradient(#f8fafc,#dce2e8);border-bottom:1px solid #bcc5ce}form{padding:16px}fieldset{border:1px solid #c8d0d7;margin:0 0 14px;padding:10px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}legend{font-weight:bold}label{display:flex;gap:8px;align-items:start;cursor:pointer}input{margin-top:5px;accent-color:#427bb5}button{font:inherit;border:1px solid #a1acb6;border-radius:3px;padding:6px 16px;margin-right:8px;background:linear-gradient(#fff,#e0e5ea);color:#34404c;cursor:pointer}p{margin:0 0 12px;color:#63717e}footer{position:sticky;bottom:0;padding:12px 0;background:#f7f8fa}button:focus-visible,input:focus-visible{outline:2px solid #427bb5;outline-offset:2px}@media(max-width:480px){fieldset{grid-template-columns:1fr}}`;shadow.append(css);
const dialog=document.createElement('dialog');dialog.setAttribute('aria-label','設定釘選功能');shadow.append(dialog);const heading=document.createElement('h2');heading.textContent='設定釘選功能';dialog.append(heading);const form=document.createElement('form');form.method='dialog';dialog.append(form);
const hint=document.createElement('p');hint.textContent='勾選左側功能，儲存後顯示於「熱門服務」上方。';form.append(hint);const checks=new Map();
for(const group of [...new Set(items.map(i=>i.group))]){const field=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=group;field.append(legend);for(const item of items.filter(i=>i.group===group)){const label=document.createElement('label'),input=document.createElement('input'),text=document.createElement('span');input.type='checkbox';text.textContent=item.label;checks.set(item.id,input);label.append(input,text);field.append(label);}form.append(field);}
const footer=document.createElement('footer'),save=document.createElement('button'),cancel=document.createElement('button');save.type='button';save.textContent='儲存';cancel.type='submit';cancel.textContent='取消';const reset=document.createElement('button');reset.type='button';reset.textContent='重置';reset.onclick=()=>{for(const input of checks.values())input.checked=false;hint.textContent='已取消所有勾選，按「儲存」套用；按「取消」保留原設定。';};footer.append(reset,save,cancel);form.append(footer);
css.textContent+=`footer{display:flex;flex-wrap:wrap;align-items:center;gap:8px}footer button{margin:0;min-height:44px;padding:6px 10px}.about-button{margin-left:auto}nav{flex:0 0 100%;display:grid;gap:4px;border-top:1px solid #c8d0d7;padding-top:8px}nav[hidden]{display:none}nav a{display:flex;align-items:center;min-height:44px;padding:0 10px;color:#285f96;border-radius:3px;text-decoration:none}nav a:hover{background:#e0e8f0;text-decoration:underline}nav a:focus-visible{outline:2px solid #427bb5;outline-offset:2px}`;
const about=document.createElement('button'),links=document.createElement('nav');about.type='button';about.className='about-button';about.textContent='關於與回饋';about.setAttribute('aria-expanded','false');about.setAttribute('aria-controls','csu-project-links');links.id='csu-project-links';links.hidden=true;links.setAttribute('aria-label','專案連結');
css.textContent+=`dialog{white-space:normal}@media(max-width:360px){footer{gap:4px}footer button{font-size:12px;padding:6px 8px}}`;
css.textContent+=`@media(max-width:650px){dialog{width:calc(100vw - 24px);max-width:none;max-height:calc(100dvh - 32px);border-radius:4px}h2{padding:14px 16px;background:linear-gradient(#f8fafc,#dce2e8)}form{padding:12px 16px 0}fieldset{padding:8px 10px;gap:2px;border-color:#d5dfe7;border-radius:4px}label{min-height:44px;box-sizing:border-box;align-items:center;padding:6px 0;line-height:1.5}input{flex:none;width:18px;height:18px;margin:0;accent-color:#245b86}footer{margin:0 -16px;padding:12px 16px max(12px,env(safe-area-inset-bottom));border-top:1px solid #d5dfe7;background:#f7f8fa}footer button{border-radius:4px}footer button:nth-child(2){background:linear-gradient(#3f78b0,#245b86);color:#fff;border-color:#245b86}}`;
// 僅在使用者點擊後開啟外部網站，不附帶學校資料或來源網址。
for(const [label,url] of [['回報問題','https://github.com/ElvisLo030/BetterCSU-Portal/issues/new'],['開發文章','https://elvislo.tw/blog/bettercsu-portal']]){const a=document.createElement('a');a.textContent=label;a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.title='在新分頁開啟';links.append(a);}
about.addEventListener('click',()=>{links.hidden=!links.hidden;about.setAttribute('aria-expanded',String(!links.hidden));});dialog.addEventListener('close',()=>{links.hidden=true;about.setAttribute('aria-expanded','false');});footer.append(about,links);
let pins=[],ready=false;
function paint(){list.replaceChildren();for(const item of items.filter(i=>pins.includes(i.id))){const li=document.createElement('li'),a=document.createElement('a');li.className='with-icon';const icon=document.createElement('span');icon.className='icon icon-bookmark';a.textContent=item.label;a.prepend(icon);const target=CSUFeatures.pinTarget(item.source.getAttribute('href'),item.source.getAttribute('onclick'),location.href);if(target){a.href=target.url;if(target.blank||item.source.target==='_blank'){a.target='_blank';a.rel='noopener';}}else{a.href='#';a.title='此功能請使用原站選單開啟';a.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();hint.textContent='此功能使用未支援的開啟方式，請從原站選單開啟。';dialog.showModal();});}li.append(a);list.append(li);}if(!list.children.length){const li=document.createElement('li'),span=document.createElement('span');span.className='csu-pin-empty';span.textContent='尚未釘選功能。點選「設定釘選功能」加入常用項目。';li.append(span);list.append(li);}}
settings.disabled=true;
settings.onclick=()=>{if(!ready)return;hint.textContent='勾選左側功能，儲存後顯示於「熱門服務」上方。';for(const [id,input] of checks)input.checked=pins.includes(id);dialog.showModal();};
save.onclick=async()=>{const next=[...checks].filter(([,input])=>input.checked).map(([id])=>id);save.disabled=true;try{await chrome.storage.local.set({csuPinnedFunctions:next});pins=next;paint();dialog.close();}catch{hint.textContent='儲存失敗，請重新載入擴充功能後再試。';}finally{save.disabled=false;}};
chrome.storage.local.get('csuPinnedFunctions').then(data=>{pins=Array.isArray(data.csuPinnedFunctions)?data.csuPinnedFunctions.filter(x=>typeof x==='string'):[];ready=true;settings.disabled=false;paint();}).catch(()=>{paint();settings.disabled=false;hint.textContent='無法讀取設定，請重新載入擴充功能。';});
chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes.csuPinnedFunctions){pins=Array.isArray(changes.csuPinnedFunctions.newValue)?changes.csuPinnedFunctions.newValue:[];paint();}});
})();
